ERROR:root:US1NMRA0022: 
Traceback (most recent call last):
  File "ghcn_multiprocessing.py", line 1736, in parse_to_netCDF
    'station_name', 'S1', ('station', 'station_name_to_char',))[:] = netCDF4.stringtochar(np.array([self.stationLongNameDict[fileId]], 'S'+str(len(self.stationLongNameDict[fileId].strip()))))
  File "utils.pyx", line 66, in netCDF4.stringtochar (netCDF4.c:3452)
ValueError: setting an array element with a sequence
